CREATE ROLE cms_owner WITH LOGIN PASSWORD 'cms_owner' NOSUPERUSER CREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE cms_runtime WITH LOGIN PASSWORD 'cms_runtime' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE DATABASE cms OWNER cms_owner;
\connect cms
GRANT CONNECT ON DATABASE cms TO cms_runtime;
GRANT USAGE ON SCHEMA public TO cms_runtime;
