"""platform identity foundation

Revision ID: 322e53ecdde5
Revises:
Create Date: 2026-08-28 18:02:25.945017
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

TENANT_TABLES = (
    "tenant_memberships",
    "tenant_roles",
    "tenant_role_permissions",
    "membership_role_assignments",
    "membership_role_scopes",
)
TENANT_ID_REFERENCE = ("tenants.id",)

revision: str = "322e53ecdde5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _timestamp_columns() -> tuple[sa.Column, sa.Column]:
    """Return standard creation and update columns for a foundation table."""

    return (
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


def upgrade() -> None:
    """Apply the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "permissions",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "role_templates",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("is_platform_role", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "tenants",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=False),
        sa.Column("short_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("primary_color", sa.String(length=7), nullable=False),
        sa.Column("accent_color", sa.String(length=7), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.CheckConstraint("key = lower(key)", name="ck_tenants_normalized_key"),
        sa.CheckConstraint(
            "status IN ('setup', 'active', 'suspended', 'closed')",
            name="ck_tenants_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "role_template_permissions",
        sa.Column("role_template_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_template_id"], ["role_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_template_id", "permission_id"),
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.CheckConstraint(
            "status IN ('invited', 'active', 'suspended', 'ended')",
            name="ck_tenant_memberships_status",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], TENANT_ID_REFERENCE, ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "account_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    op.create_table(
        "tenant_roles",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system_managed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.ForeignKeyConstraint(["template_id"], ["role_templates.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], TENANT_ID_REFERENCE, ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "key"),
    )
    op.create_table(
        "membership_role_assignments",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["tenant_roles.tenant_id", "tenant_roles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], TENANT_ID_REFERENCE, ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "membership_id", "role_id"),
    )
    op.create_table(
        "tenant_role_permissions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["tenant_roles.tenant_id", "tenant_roles.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], TENANT_ID_REFERENCE, ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("tenant_id", "role_id", "permission_id"),
    )
    op.create_table(
        "membership_role_scopes",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_reference_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.CheckConstraint(
            "scope_type IN ('institution', 'campus', 'department', 'program', "
            "'batch', 'section', 'subject_offering', 'linked_student', 'own_record')",
            name="ck_membership_role_scopes_type",
        ),
        sa.CheckConstraint(
            "(scope_type IN ('institution', 'own_record') AND scope_reference_id IS NULL) "
            "OR (scope_type NOT IN ('institution', 'own_record') "
            "AND scope_reference_id IS NOT NULL)",
            name="ck_membership_role_scopes_reference",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assignment_id"],
            ["membership_role_assignments.tenant_id", "membership_role_assignments.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], TENANT_ID_REFERENCE, ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "assignment_id",
            "scope_type",
            "scope_reference_id",
            name="uq_membership_role_scopes_resolved",
            postgresql_nulls_not_distinct=True,
        ),
    )
    # ### end Alembic commands ###

    op.create_check_constraint("ck_accounts_normalized_email", "accounts", "email = lower(email)")

    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid"
    for table_name in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table_name}_tenant_isolation ON {table_name} "
            f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
        )

    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cms_runtime') THEN
                GRANT SELECT ON tenants, permissions, role_templates,
                    role_template_permissions TO cms_runtime;
                GRANT SELECT, INSERT, UPDATE ON accounts TO cms_runtime;
                GRANT SELECT, INSERT, UPDATE, DELETE ON tenant_memberships, tenant_roles,
                    tenant_role_permissions, membership_role_assignments,
                    membership_role_scopes TO cms_runtime;
            END IF;
        END
        $$
        """
    )


def downgrade() -> None:
    """Reverse the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("membership_role_scopes")
    op.drop_table("tenant_role_permissions")
    op.drop_table("membership_role_assignments")
    op.drop_table("tenant_roles")
    op.drop_table("tenant_memberships")
    op.drop_table("role_template_permissions")
    op.drop_table("tenants")
    op.drop_table("role_templates")
    op.drop_table("permissions")
    op.drop_table("accounts")
    # ### end Alembic commands ###
