"""add applicant self service media

Revision ID: 47a171da8ce2
Revises: d684eaa982fa
Create Date: 2026-08-30 13:49:53.007762
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "47a171da8ce2"
down_revision: str | None = "d684eaa982fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ("applicant_access", "tenant_media_objects")


def _secure_table(table_name: str) -> None:
    """Enable forced tenant RLS and grant restricted runtime access."""

    op.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
    op.execute(
        sa.text(
            f"CREATE POLICY {table_name}_tenant_isolation ON {table_name} "
            "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid) "
            "WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )
    )
    op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON {table_name} TO cms_runtime"))


def upgrade() -> None:
    """Apply the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_access',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'applicant_id'], ['applicants.tenant_id', 'applicants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'membership_id'], ['tenant_memberships.tenant_id', 'tenant_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'applicant_id'),
    sa.UniqueConstraint('tenant_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'membership_id')
    )
    op.create_table('tenant_media_objects',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_membership_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'available', 'quarantined', 'deleted')", name='ck_tenant_media_objects_state'),
    sa.CheckConstraint('size_bytes > 0', name='ck_tenant_media_objects_positive_size'),
    sa.ForeignKeyConstraint(['tenant_id', 'uploaded_by_membership_id'], ['tenant_memberships.tenant_id', 'tenant_memberships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'object_key')
    )
    op.add_column('application_documents', sa.Column('media_object_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_application_documents_tenant_media_object",
        "application_documents",
        "tenant_media_objects",
        ["tenant_id", "media_object_id"],
        ["tenant_id", "id"],
        ondelete="RESTRICT",
    )
    for table_name in TABLES:
        _secure_table(table_name)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_application_documents_tenant_media_object",
        "application_documents",
        type_="foreignkey",
    )
    op.drop_column('application_documents', 'media_object_id')
    op.drop_table('tenant_media_objects')
    op.drop_table('applicant_access')
    # ### end Alembic commands ###