"""account invitations and platform roles

Revision ID: 6efef23fdb61
Revises: 60d4664a426b
Create Date: 2026-08-28 21:15:27.064003
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

ACCOUNT_REFERENCE = ("accounts.id",)
TENANT_REFERENCE = ("tenants.id",)

revision: str = "6efef23fdb61"
down_revision: str | None = "60d4664a426b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _timestamp_columns() -> tuple[sa.Column, sa.Column]:
    """Return standard creation and update columns for an identity table."""

    return (
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


def upgrade() -> None:
    """Apply the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_role_assignments",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("role_template_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.ForeignKeyConstraint(["account_id"], ACCOUNT_REFERENCE, ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["assigned_by_account_id"], ACCOUNT_REFERENCE, ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["role_template_id"], ["role_templates.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "role_template_id"),
    )
    op.create_table(
        "account_invitations",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.ForeignKeyConstraint(["account_id"], ACCOUNT_REFERENCE, ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["invited_by_account_id"], ACCOUNT_REFERENCE, ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], TENANT_REFERENCE, ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.alter_column(
        "accounts", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###

    tenant_expression = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid"
    op.execute("ALTER TABLE account_invitations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE account_invitations FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY account_invitations_tenant_isolation ON account_invitations "
        f"USING ({tenant_expression}) WITH CHECK ({tenant_expression})"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cms_runtime') THEN
                GRANT SELECT, INSERT, UPDATE ON account_invitations TO cms_runtime;
            END IF;
        END
        $$
        """
    )


def downgrade() -> None:
    """Reverse the migration."""

    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM accounts WHERE password_hash IS NULL) THEN
                RAISE EXCEPTION
                    'Cannot downgrade while invited accounts have no password';
            END IF;
        END
        $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_table("account_invitations")
    op.drop_table("platform_role_assignments")
    # ### end Alembic commands ###