"""link student document media

Revision ID: f8cd51ae2d03
Revises: 47a171da8ce2
Create Date: 2026-08-30 14:00:17.522489
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f8cd51ae2d03"
down_revision: str | None = "47a171da8ce2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student_documents", sa.Column("media_object_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_student_documents_tenant_media_object",
        "student_documents",
        "tenant_media_objects",
        ["tenant_id", "media_object_id"],
        ["tenant_id", "id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_student_documents_tenant_media_object", "student_documents", type_="foreignkey"
    )
    op.drop_column("student_documents", "media_object_id")
    # ### end Alembic commands ###